nname: Unzip and Deploy
on:
  push:
    branches: ["master", "main"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract Website Files
        run: unzip public.zip -d ./deployed_site
      - name: Fix Broken Sabayon Core Paths
        run: |
          # This replaces broken layout paths with your correct subfolder URL path configuration
          find ./deployed_site/public -type f -name "*.html" -exec sed -i 's|href="/|href="/sabayon-website-next/|g' {} +
          find ./deployed_site/public -type f -name "*.html" -exec sed -i 's|src="/|src="/sabayon-website-next/|g' {} +
          
          # Workaround for local template link errors
          find ./deployed_site/public -type f -name "*.html" -exec sed -i 's|href="css/|href="/sabayon-website-next/css/|g' {} +
          find ./deployed_site/public -type f -name "*.html" -exec sed -i 's|src="images/|src="/sabayon-website-next/images/|g' {} +
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deployed_site/public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
